version: "3.9"

services:
  frontend:
    image: gopikondaji/newfrontend:75
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mynet
  backend:
    image: gopikondaji/newbackend:5
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - mynet
    env_file:
      - ./backend/myenv
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mynet
    volumes:
      - mongodb:/data/db
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - mynet
networks:
  mynet:
    driver: bridge
volumes:
  mongodb:
